### ISSUE TITLE
Removing body tag font styles.

### ISSUE THREAD

**Issue by noahduncan** [visualmodo/borderless#1]
https://github.com/visualmodo/borderless/blob/452517ddf15eff5b1ba6290a5d03416685de239d/assets/styles/borderless.css#L3450-L3456

Can setting global body styles be removed from this plugin? The plugin is an extension of wpbakery / elementor and, in my opinion, shouldn't be configuring things like font family, line height, letter spacing, etc. on the body tag.  Using this plugin as a theme developer means I have to jump through hoops to clean out or override the styles it is configuring.

It actually surprises me to see the body tag in the css styles considering how everything else in the css file is namespaced very nicely; it's just the font styling that seems to bleed into the global scope.  

A potential solution if these styles are necessary: add a setting for the plugin that adds a class to the body tag that would allow namespacing the desired body selector. Disabling the setting would simply not add the body class and the targeted styles wouldn't apply.

**Comment by visualmodo** [comment]
Hello @noahduncan,

Thanks for your feedback. You're right, we'll resolve this in our next update. Best Regards.
